import type { Metadata } from "next";

// animate css
import "animate.css";
// import swiper css
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/thumbs";
// video player css
import "plyr-react/plyr.css";
// glightbox css
import "glightbox/dist/css/glightbox.css";
// Bootstrap and custom scss
import "assets/scss/style.scss";
import Footer from "../../components/hyundai/Footer";
import Header from "../../components/hyundai/Header";
import Container from "components/Cotainer";
import ProviderContainer from "components/ProviderContainer";

export const metadata: Metadata = {
    title: "현대엔지니어링",
    description: "Generated by create next app"
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
        <body>
        <ProviderContainer>
            <Container>
                {children}
            </Container>
        </ProviderContainer>

        <Footer/>
        </body>
        </html>
    );
}
